// Generated by CoffeeScript 1.7.1
(function() {
  this.Instabar = (function() {
    function Instabar(options) {
      var name, value;
      this.parameters = {
        "access_token": "",
        "selector": "instabar",
        'quality': "thumbnail",
        'caption': true,
        'likes': true,
        'user_id': false,
        'count': 30,
        'popular': false,
        'location': false,
        'tag': false
      };
      for (name in options) {
        value = options[name];
        this.parameters[name] = value;
      }
      this.instance_id = this._getUniqueId();
    }

    Instabar.prototype._getUniqueId = function() {
      var choices, i, text, _i;
      text = "";
      choices = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
      for (i = _i = 0; _i <= 4; i = ++_i) {
        text += choices.charAt(Math.floor(Math.random() * choices.length));
      }
      return text;
    };

    Instabar.prototype.display = function(res) {
      var caption, container, d, data, image_a, image_img, insta_bar, instance, likes, likes_count, _alert, _i, _len, _results;
      if (res.meta.code === 200) {
        container = document.getElementById(this.parameters.selector);
        insta_bar = document.createElement("div");
        insta_bar.style.textAlign = "center";
        container.appendChild(insta_bar);
        data = res.data;
        _results = [];
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          d = data[_i];
          image_a = document.createElement("a");
          image_a.href = d.link;
          image_a.target = "_blank";
          image_img = document.createElement("img");
          image_img.src = d.images[this.parameters.quality].url;
          image_img.className = "insta-pict";
          if (this.parameters.likes) {
            likes_count = d.likes.count;
            likes = document.createElement("div");
            likes.className = "likes-count";
            likes.innerHTML = "<strong class='symbol'>&#xe044;</strong>" + likes_count;
            image_a.appendChild(likes);
          }
          if (d.caption !== null) {
            image_img.alt = d.caption.text;
            if (this.parameters.caption) {
              caption = document.createElement("div");
              caption.className = "insta-caption";
              caption.innerHTML = d.caption.text.substr(0, 30);
              caption.innerHTML += "...";
              image_a.appendChild(caption);
            }
          } else {
            image_img.alt = d.id;
          }
          image_a.appendChild(image_img);
          image_a.style.position = "relative";
          image_a.className = "insta-link";
          _results.push(insta_bar.appendChild(image_a));
        }
        return _results;
      } else if (res.meta.code === 400) {
        _alert = document.createElement("span");
        _alert.innerHTML = res.meta.error_message;
        _alert.className = "alert";
        document.body.appendChild(_alert);
        setTimeout(function() {
          return _alert.className += " fading";
        }, 3000);
        instance = "instabar_" + this.instance_id;
        return delete window[instance];
      }
    };

    Instabar.prototype.run = function() {
      var instance, script, url, url_head, url_tail;
      instance = "instabar_" + this.instance_id;
      window[instance] = new Instabar(this.parameters);
      window[instance].instance_id = this.instance_id;
      url_head = "https://api.instagram.com/v1/";
      url_tail = "?count=" + this.parameters.count + "&access_token=" + this.parameters.access_token + "&callback=" + instance + ".display";
      if (this.parameters.tag) {
        url = "" + url_head + "tags/" + this.parameters.tag + "/media/recent" + url_tail;
      } else if (this.parameters.location) {
        url = "" + url_head + "locations/" + this.parameters.location + "/media/recent" + url_tail;
      } else if (this.parameters.popular) {
        url = "" + url_head + "media/popular/" + url_tail;
      } else if (this.parameters.user_id) {
        url = "" + url_head + "users/" + this.parameters.user_id + "/media/recent/" + url_tail;
      } else {
        url = "" + url_head + "users/self/feed/" + url_tail;
      }
      script = document.createElement("script");
      script.id = "instfeed-fetcher";
      script.src = url;
      return document.body.appendChild(script);
    };

    return Instabar;

  })();

}).call(this);
